### ISSUE TITLE
Failure to build with statistics 0.14.0.0

### ISSUE THREAD

**Issue by erikd** [bos/criterion#140]
Seems the statistics 0.14.0.o break criterion. Now getting:
```
[ 2 of 13] Compiling Criterion.Types  ( Criterion/Types.hs, /home/erikd/Git/Haskell/criterion/dist-newstyle/build/criterion-1.1.4.0/build/Criterion/Types.o )

Criterion/Types.hs:554:33: error:
    Not in scope: type constructor or class ‘B.Estimate’
    Module ‘Statistics.Resampling.Bootstrap’ does not export ‘Estimate’.

Criterion/Types.hs:556:22: error:
    Not in scope: type constructor or class ‘B.Estimate’
    Module ‘Statistics.Resampling.Bootstrap’ does not export ‘Estimate’.

Criterion/Types.hs:579:23: error:
    Not in scope: type constructor or class ‘B.Estimate’
    Module ‘Statistics.Resampling.Bootstrap’ does not export ‘Estimate’.

Criterion/Types.hs:581:23: error:
    Not in scope: type constructor or class ‘B.Estimate’
    Module ‘Statistics.Resampling.Bootstrap’ does not export ‘Estimate’.
```

**Comment by RyanGlScott** [comment]
Indeed. Luckily, there are [upper version bounds in place](http://hackage.haskell.org/package/criterion-1.1.4.0/revisions/) on `criterion` on Hackage, so you shouldn't hit this error unless you specifically ask for `statistics-0.14`.

This would be fixed by either #137 or #139.

**Comment by erikd** [comment]
> so you shouldn't hit this error unless you specifically ask for statistics-0.14

Or try to build from Git. Would be nice to get the bounds for statistics fixed in git while the other two issues are worked on

**Comment by RyanGlScott** [comment]
> Or try to build from Git.

Oh dear, I didn't notice that the repo is out-of-sync with Hackage in this regard. Eek.

Unfortunately, due to a series of unusual circumstances, I have push access for `criterion` on Hackage, but not on GitHub, so I can't do the latter. But I do know someone who does, so once #139 is in a manageable state, I'll work on getting that merged ASAP.

**Comment by erikd** [comment]
@RyanGlScott You should be made a collaborator :)

**Comment by RyanGlScott** [comment]
Fixed in https://github.com/bos/criterion/pull/141. I'll work on uploading a new version to Hackage soon.
